package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// DefaultPhpIni holds dev-optimized PHP ini settings.
var DefaultPhpIni = map[string]string{
	"error_reporting":                 "E_ALL",
	"display_errors":                  "On",
	"display_startup_errors":          "On",
	"log_errors":                      "On",
	"memory_limit":                    "512M",
	"max_execution_time":              "300",
	"max_input_time":                  "300",
	"upload_max_filesize":             "256M",
	"post_max_size":                   "256M",
	"max_input_vars":                  "5000",
	"opcache.enable":                  "1",
	"opcache.revalidate_freq":         "0",
	"opcache.validate_timestamps":     "1",
	"opcache.max_accelerated_files":   "20000",
	"opcache.memory_consumption":      "256",
	"opcache.interned_strings_buffer": "32",
	"realpath_cache_size":             "4096k",
	"realpath_cache_ttl":              "600",
	"session.gc_maxlifetime":          "86400",
	"date.timezone":                   "UTC",
	"zend.assertions":                 "1",
}

// DefaultMysqlCnf holds dev-optimized MySQL server settings.
var DefaultMysqlCnf = map[string]string{
	"skip-log-bin":                   "",
	"innodb_flush_log_at_trx_commit": "0",
	"innodb_flush_method":            "O_DIRECT",
	"innodb_buffer_pool_size":        "512M",
	"innodb_log_file_size":           "128M",
	"innodb_doublewrite":             "0",
	"innodb_io_capacity":             "2000",
	"innodb_io_capacity_max":         "4000",
	"max_connections":                "200",
	"table_open_cache":               "4000",
	"performance_schema":             "OFF",
	"slow_query_log":                 "1",
	"long_query_time":                "2",
	"host_cache_size":                "0",
	"skip-name-resolve":              "",
}

// ProtectedMysqlCnf holds keys that are always forced and cannot be overridden.
var ProtectedMysqlCnf = map[string]string{
	"ssl": "0",
}

// WritePhpIni writes a nova-overrides.ini file to devDir/php/{version}/conf.d/.
func WritePhpIni(devDir, phpVersion string, settings map[string]string) error {
	dir := filepath.Join(devDir, "php", phpVersion, "conf.d")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating php conf.d dir: %w", err)
	}

	content := formatIni(settings)
	path := filepath.Join(dir, "nova-overrides.ini")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// WriteMysqlCnf writes a nova-overrides.cnf file to devDir/mysql/conf.d/.
func WriteMysqlCnf(devDir string, settings map[string]string) error {
	dir := filepath.Join(devDir, "mysql", "conf.d")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating mysql conf.d dir: %w", err)
	}

	content := formatCnf(settings)
	path := filepath.Join(dir, "nova-overrides.cnf")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

func formatIni(settings map[string]string) string {
	var b strings.Builder
	b.WriteString("; Generated by nova — do not edit manually\n")

	keys := sortedKeys(settings)
	for _, k := range keys {
		fmt.Fprintf(&b, "%s = %s\n", k, settings[k])
	}
	return b.String()
}

func formatCnf(settings map[string]string) string {
	var b strings.Builder
	b.WriteString("; Generated by nova — do not edit manually\n")
	b.WriteString("[mysqld]\n")

	keys := sortedKeys(settings)
	for _, k := range keys {
		v := settings[k]
		if v == "" {
			fmt.Fprintf(&b, "%s\n", k)
		} else {
			fmt.Fprintf(&b, "%s = %s\n", k, v)
		}
	}
	return b.String()
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// MergeSettings merges settings maps in order: defaults → global → project.
// Later layers override earlier ones. Returns a new map.
func MergeSettings(defaults, global, project map[string]string) map[string]string {
	merged := make(map[string]string)
	for k, v := range defaults {
		merged[k] = v
	}
	for k, v := range global {
		merged[k] = v
	}
	for k, v := range project {
		merged[k] = v
	}
	return merged
}
