package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestMergeSettings_DefaultsOnly(t *testing.T) {
	t.Parallel()
	defaults := map[string]string{"memory_limit": "512M", "display_errors": "On"}

	got := MergeSettings(defaults, nil, nil)

	if got["memory_limit"] != "512M" {
		t.Errorf("memory_limit = %q, want %q", got["memory_limit"], "512M")
	}
	if got["display_errors"] != "On" {
		t.Errorf("display_errors = %q, want %q", got["display_errors"], "On")
	}
}

func TestMergeSettings_GlobalOverridesDefaults(t *testing.T) {
	t.Parallel()
	defaults := map[string]string{"memory_limit": "512M"}
	global := map[string]string{"memory_limit": "1G"}

	got := MergeSettings(defaults, global, nil)

	if got["memory_limit"] != "1G" {
		t.Errorf("memory_limit = %q, want %q", got["memory_limit"], "1G")
	}
}

func TestMergeSettings_ProjectOverridesGlobal(t *testing.T) {
	t.Parallel()
	defaults := map[string]string{"memory_limit": "512M"}
	global := map[string]string{"memory_limit": "1G"}
	project := map[string]string{"memory_limit": "2G"}

	got := MergeSettings(defaults, global, project)

	if got["memory_limit"] != "2G" {
		t.Errorf("memory_limit = %q, want %q", got["memory_limit"], "2G")
	}
}

func TestMergeSettings_AddsNewKeys(t *testing.T) {
	t.Parallel()
	defaults := map[string]string{"memory_limit": "512M"}
	global := map[string]string{"upload_max_filesize": "100M"}
	project := map[string]string{"max_execution_time": "600"}

	got := MergeSettings(defaults, global, project)

	if got["memory_limit"] != "512M" {
		t.Errorf("memory_limit = %q, want %q", got["memory_limit"], "512M")
	}
	if got["upload_max_filesize"] != "100M" {
		t.Errorf("upload_max_filesize = %q, want %q", got["upload_max_filesize"], "100M")
	}
	if got["max_execution_time"] != "600" {
		t.Errorf("max_execution_time = %q, want %q", got["max_execution_time"], "600")
	}
}

func TestMergeSettings_NilInputs(t *testing.T) {
	t.Parallel()
	got := MergeSettings(nil, nil, nil)

	if got == nil {
		t.Error("expected empty map, got nil")
	}
	if len(got) != 0 {
		t.Errorf("expected empty map, got %v", got)
	}
}

func TestWritePhpIni(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	settings := map[string]string{
		"memory_limit":            "1G",
		"display_errors":          "On",
		"opcache.revalidate_freq": "0",
	}

	err := WritePhpIni(dir, "8.2", settings)
	if err != nil {
		t.Fatalf("WritePhpIni() error = %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, "php", "8.2", "conf.d", "nova-overrides.ini"))
	if err != nil {
		t.Fatalf("reading ini file: %v", err)
	}

	s := string(content)
	if !strings.Contains(s, "memory_limit = 1G") {
		t.Errorf("missing memory_limit setting in:\n%s", s)
	}
	if !strings.Contains(s, "display_errors = On") {
		t.Errorf("missing display_errors setting in:\n%s", s)
	}
	if !strings.Contains(s, "; Generated by nova") {
		t.Errorf("missing generated header in:\n%s", s)
	}
}

func TestWriteMysqlCnf(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	settings := map[string]string{
		"innodb_buffer_pool_size": "1G",
		"max_connections":         "500",
		"skip-log-bin":            "",
		"ssl":                     "0",
	}

	err := WriteMysqlCnf(dir, settings)
	if err != nil {
		t.Fatalf("WriteMysqlCnf() error = %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, "mysql", "conf.d", "nova-overrides.cnf"))
	if err != nil {
		t.Fatalf("reading cnf file: %v", err)
	}

	s := string(content)
	if !strings.Contains(s, "[mysqld]") {
		t.Errorf("missing [mysqld] section in:\n%s", s)
	}
	if !strings.Contains(s, "innodb_buffer_pool_size = 1G") {
		t.Errorf("missing innodb_buffer_pool_size in:\n%s", s)
	}
	if !strings.Contains(s, "skip-log-bin\n") {
		t.Errorf("flag-style skip-log-bin should have no value in:\n%s", s)
	}
	if !strings.Contains(s, "ssl = 0") {
		t.Errorf("missing ssl setting in:\n%s", s)
	}
}

func TestWriteMysqlCnf_ProtectedKeysApplied(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	settings := MergeSettings(DefaultMysqlCnf, nil, nil)
	for k, v := range ProtectedMysqlCnf {
		settings[k] = v
	}

	err := WriteMysqlCnf(dir, settings)
	if err != nil {
		t.Fatalf("WriteMysqlCnf() error = %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, "mysql", "conf.d", "nova-overrides.cnf"))
	if err != nil {
		t.Fatalf("reading cnf file: %v", err)
	}

	if !strings.Contains(string(content), "ssl = 0") {
		t.Errorf("protected ssl key missing in:\n%s", string(content))
	}
}
