// Code generated by fetchversions; DO NOT EDIT.

package config

var PHPVersions = []string{"8.5", "8.4", "8.3", "8.2"}
var NodeVersions = []string{"25", "24", "22", "20"}
var MySQLVersions = []string{"9.6", "9.5", "9.4", "9.3", "9.2", "9.1", "9.0", "8.4", "8.3", "8.2", "8.1", "8.0", "5.7", "5.6", "5.5"}
var PostgresVersions = []string{"18", "17", "16", "15", "14", "13"}
var RedisVersions = []string{"8", "7", "6"}
